server.port=8080

spring.datasource.url=jdbc.postgresql://saigoud73:IRnF3pdvceFvl2cj5CF9CcYAWIkneSut@dpg-d76e5e6a2pns73em8uj0-a.oregon-postgres.render.com/musicdb_68py
spring.datasource.username=<saigoud73>
spring.datasource.password=<IRnF3pdvceFvl2cj5CF9CcYAWIkneSut>
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.application.name=music-player-backend
