server.port=8080

spring.datasource.url=jdbc:mysql://<host>:<port>/<musicdb_68py>?useSSL=false&serverTimezone=UTC
spring.datasource.username=<saigoud73>
spring.datasource.password=<IRnF3pdvceFvl2cj5CF9CcYAWIkneSut>
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.application.name=music-player-backend
